#!/usr/bin/env bash
set -e

pip install -e .

## get geography info for all countries and population info for most
python codes/data/multi_country/get_adm_info.py


## data scraping and processing

# CHN
python codes/data/china/collate_data.py

# FRA
Rscript codes/data/france/scrape_conf_cases_by_region.R
stata -b do codes/data/frgiance/format_infected.do
stata -b do codes/data/france/format_policy.do

# IRN
Rscript codes/data/iran/iran_cleaning.R
python codes/data/iran/iran-split-interim-into-processed.py

# ITA
python codes/data/italy/italy-download-cases-merge-policies.py

# KOR
Rscript codes/data/korea/download_and_clean_JHU_southkorea_data.R
Rscript codes/data/korea/generate_KOR_interim.R
python codes/data/korea/korea-interim-to-processed.py

# USA
Rscript codes/data/usa/download_and_clean_JHU_usa_data.R
python codes/data/usa/download_latest_covidtrackingdotcom_data.py
jupyter nbconvert --ExecutePreprocessor.timeout=None --ExecutePreprocessor.kernel_name=python3 --execute codes/data/usa/add_testing_regimes_to_covidtrackingdotcom_data.ipynb
python codes/data/usa/merge_policy_and_cases.py
python codes/data/usa/filter-processed-to-end-date.py


## regression model estimation
stata -b do codes/models/alt_growth_rates/MASTER_run_all.do


## SIR model projection
python codes/models/get_gamma.py
Rscript codes/models/run_all_CB_simulations.R


## Figures and tables

# Fig 1
Rscript codes/plotting/fig1.R

# Fig 2
Rscript codes/plotting/fig2.R

# Fig 3
# created by regression model estimation

# Fig 4
python codes/plotting/gen_fig4.py
python codes/plotting/fig4_analysis.py

# Table A1
python codes/plotting/count-policies.py

# Figure A1
# created by regression model estimatoin

# Figure A2
python codes/plotting/figA2.py
