#!/usr/bin/env bash
set -e

pip install -e .


## parse flags to not run certain things
STATA=true
CENSUS=true
NUMPROJ=1000
DOWNLOAD=true
for arg in "$@"
do
    case $arg in
        -s|--nostata)
            STATA=false
            shift
        ;;
        -c|--nocensus)
            CENSUS=false
            shift
        ;;
        -p|--num-proj)
            NUMPROJ="$2"
            shift
            shift
        ;;
      	-d|--no-download)
      	    DOWNLOAD=false
      	    shift
      	;;
    esac

done


## data scraping and processing


### Geography/population
printf "***Downloading shape and population info for all countries***\n"
if $CENSUS
then
    python codes/data/multi_country/get_adm_info.py
fi

### Policy
printf "***Downloading USA testing data***\n"
if $DOWNLOAD
then
    python codes/data/usa/download_latest_covidtrackingdotcom_data.py
    python codes/data/usa/add_testing_regimes_to_covidtrackingdotcom_data.py
fi

### Epi
#### Multi-country
printf "***Downloading Johns Hopkins U data for all countries***\n"
if $DOWNLOAD
then
    Rscript codes/data/multi_country/download_6_countries_JHU.R
fi

#### FRA
printf "***Processing FRA epi data***\n"
if $STATA
then
    stata -b do codes/data/france/format_infected.do
fi

#### USA
printf "***Processing USA epi data***\n"
if $DOWNLOAD
then
    Rscript codes/data/usa/download_and_clean_usafacts.R
fi

### Dataset merging
#### CHN
printf "***Processing and merging CHN data***\n"
python codes/data/china/collate_data.py

#### FRA
printf "***Merging FRA data***\n"
if $STATA
then
    stata -b do codes/data/france/format_policy.do
fi

# IRN
printf "***Processing  and merging IRN data***\n"
Rscript codes/data/iran/iran_cleaning.R
python codes/data/iran/iran-split-interim-into-processed.py

# ITA
printf "***Processing  and merging ITA data***\n"
if $DOWNLOAD
then
    python codes/data/italy/italy-download-cases-merge-policies.py
else
    python codes/data/italy/italy-download-cases-merge-policies.py --nr
fi

# KOR
printf "***Processing  and merging KOR data***\n"
Rscript codes/data/korea/generate_KOR_processed.R

# USA
printf "***Merging USA data***\n"
python codes/data/usa/merge_policy_and_cases.py

# quality-check processed datasets
printf "***Checking processed data***\n"
python codes/data/multi_country/quality-check-processed-datasets.py

## regression model estimation
printf "***Estimating regression model and creating Figure 3 and A1***\n"
if $STATA
then
    stata -b do codes/models/alt_growth_rates/MASTER_run_all_reg.do
fi


## SIR model projection
printf "***Projecting infections***\n"
python codes/models/get_gamma.py
Rscript codes/models/run_all_CB_simulations.R $NUMPROJ

# This one outputs all the raw projection output for diagnostic purposes.
Rscript codes/models/output_underlying_projection_output.R

## Figures and tables

# Fig 1
printf "***Creating Fig 1***\n"
Rscript codes/plotting/fig1.R

# Fig 2
printf "***Creating Fig 2***\n"
Rscript codes/plotting/fig2.R

# Fig 3
# created by regression model estimation

# Fig 4
printf "***Creating Fig 4***\n"
python codes/plotting/gen_fig4.py
python codes/plotting/fig4_analysis.py

# Table A1
printf "***Creating Table A1***\n"
python codes/plotting/count-policies.py

# Figure A1
# created by regression model estimation

# Figure A2
printf "***Creating Fig A2***\n"
if $DOWNLOAD
then
    python codes/plotting/figA2.py
else
    python codes/plotting/figA2.py --nd
fi

# Figure AX (Projection with multiple gamma plot - replace this text when numbered)
printf "***Creating ED Fig 8***\n"
Rscript codes/models/run_projection_with_multiple_gammas.R
